### ISSUE TITLE
add handlers for SIGTERM and SIGUSR2

### ISSUE THREAD

**Issue by d-v-b** [JaneliaSciComp/dask-janelia#2]
i.e., copy @stuarteberg's [code](https://github.com/janelia-flyem/flyemflows/blob/master/flyemflows/__init__.py#L21-L27) and add the relevant preload to the example distributed config, e.g.
```yaml
distributed:
  worker:
    preload:
    - dask_janelia.register_signal_handlers
```
